FROM archlinux:latest as builder

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    gcc \
    make \
    curl \
    libbsd \
    && pacman -Scc --noconfirm

WORKDIR /app
COPY . /app
RUN gcc -o myapp client.c -lssl

FROM archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    libbsd \
    && pacman -Scc --noconfirm

WORKDIR /app
COPY --from=builder /app/myapp /app/myapp

EXPOSE 8080
CMD ["./myapp"]

